In [1]:
import numpy as np

### Task 1
Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно


In [4]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

### Task 2
Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.


In [12]:
a1 = a.reshape(3, 4)
a2 = a.reshape(4, 3)
a3 = a.reshape(2, 6)
a4 = a.reshape(6, 2)
a5 = a.reshape(12, 1)
a1, a2, a3, a4, a5

(array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]),
 array([[12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]]))

### Task 3
Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).


In [20]:
a6 = a.reshape(-1, 3)
a7 = a.reshape(-1, 4)
a8 = a.reshape(6, -1)
a9 = a.reshape(2, -1)
a10 = a.reshape(12, -1)
a6, a7, a8, a9, a10

(array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23]]))

Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?
Ответ: нет

### Task 5
Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.


In [21]:
a = np.random.randn(3, 4)
a

array([[-2.02471016, -0.56709856, -0.59404458, -1.01115025],
       [-1.50449117, -0.20476349, -0.29330422, -0.14762188],
       [ 0.43683367,  0.47539051,  0.75776671,  0.39903687]])

In [22]:
b = a.flatten()
b

array([-2.02471016, -0.56709856, -0.59404458, -1.01115025, -1.50449117,
       -0.20476349, -0.29330422, -0.14762188,  0.43683367,  0.47539051,
        0.75776671,  0.39903687])

In [23]:
a.size, b.size

(12, 12)

### Task 6
Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.


In [28]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

### Task 7
Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [29]:
b = np.arange(20, 1, -2)
b

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [30]:
np.array_equal(a, b)

True

Ответ: нет разницы

### Task 8
Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [32]:
a = np.zeros((2, 2))
b = np.ones((3, 2))
a, b

(array([[0., 0.],
        [0., 0.]]),
 array([[1., 1.],
        [1., 1.],
        [1., 1.]]))

In [35]:
v = np.concatenate((a, b), axis=0)
v

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [36]:
v.size

10

### Task 9
Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?


In [42]:
a = np.arange(0, 12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [43]:
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [44]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [46]:
B = A.dot(At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [47]:
B.size

16

In [48]:
np.linalg.det(B)

0.0

Ответ: Размер 4 * 4 (число строк на число столбцов), вычислить обратную нельзя, так как определитель равен нулю.

### Task 10
Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.


In [49]:
np.random.seed(42)

### Task 11
Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 


In [52]:
c = np.random.randint(0, 16, 16)
c

array([10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4,  3,  7,  7,  2])

### Task 12
Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [62]:
C = c.reshape(4, 4)
C1 = C * 10
D = C1 + B
C, D

(array([[10,  7, 12,  4],
        [ 6,  9,  2,  6],
        [10, 10,  7,  4],
        [ 3,  7,  7,  2]]),
 array([[105,  84, 143,  72],
        [ 74, 140, 106, 182],
        [123, 186, 219, 252],
        [ 62, 192, 282, 322]]))

In [56]:
np.linalg.det(D)

-21791999.99999994

In [57]:
np.linalg.matrix_rank(D)

4

In [58]:
D_inv = np.linalg.inv(D)
D_inv

array([[-0.02740639, -0.04324615,  0.06958333, -0.02388491],
       [ 0.05778084,  0.09026156, -0.11791667,  0.02834526],
       [ 0.01406938,  0.00293227, -0.01875   ,  0.00987059],
       [-0.0414978 , -0.04806167,  0.07333333, -0.01784141]])

### Task 13
Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.


In [59]:
D_inv = np.where(D_inv > 0, 1, 0)
D_inv

array([[0, 0, 1, 0],
       [1, 1, 0, 1],
       [1, 1, 0, 1],
       [0, 0, 1, 0]])

In [68]:
E = np.where(D_inv, B, C)
print(f'C: {C}\nB: {B}\nE: {E}')

C: [[10  7 12  4]
 [ 6  9  2  6]
 [10 10  7  4]
 [ 3  7  7  2]]
B: [[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
E: [[ 10   7  23   4]
 [ 14  50   2 122]
 [ 23  86   7 212]
 [  3   7 212   2]]
